[project]
name = "arcospheres"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nyctef", email = "nyctef@nyctef.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
arcospheres = "arcospheres:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
